version: "3.8"
services:
  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  api:
    build:
      context: packages/outpostapi
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - ALLOWED_HOSTS=api,localhost
      - SECRET_KEY=fakesecret
      - DB_USER=postgres
      - DB_PASS=postgres
    ports:
      - "8000:8000"
  client:
    build:
      context: packages/outpost-client
      dockerfile: Dockerfile
    ports:
      - "5173:80"
volumes:
  db:
    driver: local
