# Generated by Django 4.2 on 2023-04-16 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_character_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='user_id',
            new_name='user',
        ),
    ]
