# Generated by Django 4.2 on 2023-05-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_perk_characterperk'),
    ]

    operations = [
        migrations.AddField(
            model_name='perk',
            name='max_active',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='characterperk',
            name='active',
            field=models.IntegerField(default=0),
        ),
    ]
