# Generated by Django 4.2 on 2023-05-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_perk_max_active_alter_characterperk_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perk',
            name='max_active',
            field=models.IntegerField(default=1),
        ),
    ]
