# Generated by Django 4.2 on 2023-05-04 18:23

from django.db import migrations

def create_perks(apps, schema_editor):
    Perk = apps.get_model('characters', 'Perk')
    Perk.objects.create(class_name="drifter", order=0, max_active=3, description="Replace one <modMinus1/> card with one <modPlus1/> card")
    Perk.objects.create(class_name="drifter", order=1, max_active=1, description="Replace one <modMinus2/> card with one <modPlus0/> card")
    Perk.objects.create(class_name="drifter", order=2, max_active=2, description="Replace one <modPlus1/> card with two <modPlus0/> \"Move one of your character tokens backward one slot\" cards")
    Perk.objects.create(class_name="drifter", order=3, max_active=1, description="Replace two <modPlus0/> cards with two <pierce/> 3 <rolling/> cards")
    Perk.objects.create(class_name="drifter", order=4, max_active=1, description="Replace two <modPlus0/> cards with two <push/> 2 <rolling/> cards")
    Perk.objects.create(class_name="drifter", order=5, max_active=1, description="Add one <modPlus3/> card")
    Perk.objects.create(class_name="drifter", order=6, max_active=2, description="Add one <modPlus2/> <immobilize/> card")
    Perk.objects.create(class_name="drifter", order=7, max_active=1, description="Add two \"<heal/>1, self\" <rolling/> cards")
    Perk.objects.create(class_name="drifter", order=8, max_active=1, description="Ignore scenario effects and add one <modPlus1/> card")
    Perk.objects.create(class_name="drifter", order=9, max_active=1, description="Ignore item <minus1ModCard/> effects and add one <modPlus1/> card")
    Perk.objects.create(class_name="drifter", order=10, max_active=2, description="Whenever you long rest you may move one of your character tokens backward one slot")
    Perk.objects.create(class_name="drifter", order=11, max_active=1, description="You may bring one additional <equipSlotSingleHand/> item into each scenario")
    Perk.objects.create(class_name="drifter", order=12, max_active=1, description="At the end of each scenario, you may discard up to two loot cards, except _Random Item_, to draw that many new loot cards")


    Perk.objects.create(class_name="deathwalker", order=0, max_active=1, description="Remove two <modMinus1/> cards")
    Perk.objects.create(class_name="deathwalker", order=1, max_active=1, description="Replace one <modMinus2/> card with one <modPlus0/> card")
    Perk.objects.create(class_name="deathwalker", order=2, max_active=3, description="Replace one <modMinus1/> card with one <modPlus1/> card")
    Perk.objects.create(class_name="deathwalker", order=3, max_active=3, description="Replace one <modPlus0/> card with one <modPlus1/> <curse/> card")
    Perk.objects.create(class_name="deathwalker", order=4, max_active=2, description="Add one <modPlus2/> <dark/> card")
    Perk.objects.create(class_name="deathwalker", order=5, max_active=2, description="Add one <rolling/> <disarm/> and one <rolling/> <muddle/> card")
    Perk.objects.create(class_name="deathwalker", order=6, max_active=2, description="Add two <rolling/> \"<heal/>1, ally\" cards")
    Perk.objects.create(class_name="deathwalker", order=7, max_active=1, description="Ignore negative scenario effects")
    Perk.objects.create(class_name="deathwalker", order=8, max_active=1, description="Whenever you long rest, you may move one <shadow/> up to 3 hexes")
    Perk.objects.create(class_name="deathwalker", order=9, max_active=1, description="While you occupy a hex with a <shadow/>, all attacks targeting you gain Disadvantage")
    Perk.objects.create(class_name="deathwalker", order=10, max_active=1, description="Whenever you short rest you may <darkRemove/> to perform \"<curse/>, <range/>2\" as if you were occupying a hex with a <shadow/>")


    Perk.objects.create(class_name="boneshaper", order=0, max_active=2, description="Replace one <modMinus1/> card with <modPlus0/> <curse/> card")
    Perk.objects.create(class_name="boneshaper", order=1, max_active=1, description="Replace one <modMinus1/> card with one <modPlus0/> <poison/> card")
    Perk.objects.create(class_name="boneshaper", order=2, max_active=1, description="Replace one <modMinus2/> card with one <modPlus0/>")
    Perk.objects.create(class_name="boneshaper", order=3, max_active=3, description="Replace one <modPlus0/> card with one <modPlus1/> \"Kill the attacking summon to instead add <modPlus4/>\" card")
    Perk.objects.create(class_name="boneshaper", order=4, max_active=2, description="Add three <rolling/> \"<heal/>1, <target/><boneshaper/>\" cards")
    Perk.objects.create(class_name="boneshaper", order=5, max_active=3, description="Add one <modPlus2/> <earth/>/<dark/> card")
    Perk.objects.create(class_name="boneshaper", order=6, max_active=1, description="Ignore negative scenario effects and add two <modPlus1/> cards")
    Perk.objects.create(class_name="boneshaper", order=7, max_active=1, description="Immediately before each of your rests, you may kill one of your summons to perform \"<bless/>, self\"")
    Perks.objects.create(class_name="boneshaper", order=8, max_active=1, description="Once per scenario, when any character ally would become exhausted by suffering <damage/>, you may suffer 2 <damage/> to reduce their hit point value to 1 instead")
    Perk.objects.create(class_name="boneshaper", order=9, max_active=2, description="At the start of each scenario, you may play a level 1 card from your hand to perform a summon action of the card")

    Perk.objects.create(class_name="geminate", order=0, max_active=1, description="Replace one <modMinus2/> card with one <modPlus0/> card")
    // TODO damn data entry isn't fun... I'll do this later

def remove_perks(apps, schema_editor):
    Perk = apps.get_model('characters', 'Perk')
    Perk.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_alter_perk_max_active'),
    ]

    operations = [
        migrations.RunPython(create_perks, remove_perks),
    ]
