# Generated by Django 4.2 on 2023-05-06 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_add_perks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('class_name', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'masteries',
                'ordering': ['order'],
                'unique_together': {('class_name', 'order')},
            },
        ),
        migrations.CreateModel(
            name='CharacterMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
                ('mastery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.mastery')),
            ],
            options={
                'verbose_name_plural': 'character masteries',
                'unique_together': {('character', 'mastery')},
            },
        ),
    ]
