# Generated by Django 4.2 on 2023-05-04 18:23

from django.db import migrations

def create_masteries(apps, schema_editor):
    Mastery = apps.get_model('characters', 'Mastery')

    Mastery.objects.create(class_name="drifter", order=0, description="End a scenario with your character tokens on the last use slots of four persistent abilities")
    Mastery.objects.create(class_name="drifter", order=1, description="Never perform a move or attack ability with a value less than 4, and perform at least one move or attack ability every round")

    Mastery.objects.create(class_name="boneshaper", order=0, description="Kill at least 15 of your summons")
    Mastery.objects.create(class_name="boneshaper", order=1, description="Play a summon action on your first turn, have this summon kill at least 6 enemies, and keep it alive for the entire scenario")

    Mastery.objects.create(class_name="bannerspear", order=0, description="Attack at least three targets with three different area of effect attack abilities")
    Mastery.objects.create(class_name="bannerspear", order=1, description="Play a Banner summon ability on your first turn, always have it within <range/> 3 of you, and keep it alive for the entire scenario")

    Mastery.objects.create(class_name="geminate", order=0, description="Switch forms every round")
    Mastery.objects.create(class_name="geminate", order=1, description="Lose at least one card every round")

    Mastery.objects.create(class_name="blinkblade", order=0, description="Declare Fast seven rounds in a row")
    Mastery.objects.create(class_name="blinkblade", order=1, description="Never be targeted by an attack")

    Mastery.objects.create(class_name="deathwalker", order=0, description="Consume seven <shadow/> in one round")
    Mastery.objects.create(class_name="deathwalker", order=1, description="Create or consume at least one <shadow/> every round")

def remove_masteries(apps, schema_editor):
    Mastery = apps.get_model('characters', 'Mastery')
    Mastery.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0009_mastery_charactermastery'),
    ]

    operations = [
        migrations.RunPython(create_masteries, remove_masteries),
    ]
