# Generated by Django 4.2 on 2023-05-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0010_add_masteries'),
    ]

    operations = [
        migrations.AddField(
            model_name='perk',
            name='connected',
            field=models.BooleanField(default=False),
        ),
    ]
