# Generated by Django 4.2 on 2023-05-04 18:23

from django.db import migrations


def fix_perks(apps, schema_editor):
    Perk = apps.get_model('characters', 'Perk')
    Perk.objects.filter(class_name="drifter", order=10).update(connected=True)
    Perk.objects.filter(class_name="boneshaper",
                        order=9).update(connected=True)
    Perk.objects.filter(class_name="geminate",
                        order=11).update(connected=True)
    Perk.objects.filter(class_name="bannerspear",
                        order=9).update(connected=True)


def unfix_perks(apps, schema_editor):
    Perk = apps.get_model('characters', 'Perk')
    Perk.objects.filter(class_name="drifter", order=10).update(connected=False)
    Perk.objects.filter(class_name="boneshaper",
                        order=9).update(connected=False)
    Perk.objects.filter(class_name="geminate",
                        order=11).update(connected=False)
    Perk.objects.filter(class_name="bannerspear",
                        order=9).update(connected=False)


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0011_perk_connected'),
    ]

    operations = [
        migrations.RunPython(fix_perks, unfix_perks),
    ]
