# Generated by Django 4.2 on 2023-05-04 18:23

from django.db import migrations


def fix_perks(apps, schema_editor):
    Perk = apps.get_model('characters', 'Perk')
    Perk.objects.filter(class_name="boneshaper",
                        order=1).update(max_active=2)


def unfix_perks(apps, schema_editor):
    Perk = apps.get_model('characters', 'Perk')
    Perk.objects.filter(class_name="boneshaper",
                        order=1).update(max_active=1)


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0013_add_non_starter_perks'),
    ]

    operations = [
        migrations.RunPython(fix_perks, unfix_perks),
    ]
