# Generated by Django 4.2 on 2023-05-18 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('characters', '0010_add_masteries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(verbose_name='created at')),
                ('notes', models.TextField(blank=True, null=True)),
                ('hide', models.IntegerField(default=0)),
                ('metal', models.IntegerField(default=0)),
                ('wood', models.IntegerField(default=0)),
                ('arrowvine', models.IntegerField(default=0)),
                ('axenut', models.IntegerField(default=0)),
                ('corpsecap', models.IntegerField(default=0)),
                ('flamefruit', models.IntegerField(default=0)),
                ('rockroot', models.IntegerField(default=0)),
                ('snowthistle', models.IntegerField(default=0)),
                ('morale', models.IntegerField(default=0)),
                ('soldiers', models.IntegerField(default=0)),
                ('barracks_level', models.IntegerField(default=0)),
                ('inspiration', models.IntegerField(default=0)),
                ('total_defense', models.IntegerField(default=0)),
                ('prosperity', models.IntegerField(default=0)),
                ('perk_tags', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('section', models.CharField(max_length=200)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('campaign', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CampaignCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
            ],
            options={
                'unique_together': {('campaign', 'character')},
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='characters',
            field=models.ManyToManyField(through='campaigns.CampaignCharacter', to='characters.character'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='users',
            field=models.ManyToManyField(through='campaigns.CampaignUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TownGuardPerk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.IntegerField(default=0)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
                ('perk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.perk')),
            ],
            options={
                'unique_together': {('campaign', 'perk')},
            },
        ),
    ]
