# Generated by Django 4.2 on 2023-05-21 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='townguardperk',
            options={'ordering': ['order']},
        ),
        migrations.AlterUniqueTogether(
            name='townguardperk',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='townguardperk',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='townguardperk',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='townguardperk',
            name='sections',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='townguardperk',
            name='active',
        ),
        migrations.RemoveField(
            model_name='townguardperk',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='townguardperk',
            name='perk',
        ),
        migrations.CreateModel(
            name='ActiveTownGuardPerk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.TextField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
                ('perk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.townguardperk')),
            ],
            options={
                'unique_together': {('campaign', 'perk')},
            },
        ),
    ]
