# Generated by Django 4.2 on 2023-05-04 18:23

from django.db import migrations


def create_perks(apps, schema_editor):
    TownGuardPerk = apps.get_model('campaigns', 'TownGuardPerk')
    TownGuardPerk.objects.create(order=0, sections="19.2;178.3",
                                 description="Replace one <modMinus10/> card with one <modPlus30/> card and one <modMinus20/> \"Gain any one material resource\" card")
    TownGuardPerk.objects.create(order=1, sections="17.2;166.4",
                                 description="Replace two <modPlus10/> cards with one <modPlus30/> card and one <modMinus20/> \"Gain any two material resources\" card")
    TownGuardPerk.objects.create(order=2, sections="151.3;194.3",
                                 description="Replace one <modPlus10/> card with one <modPlus10/> card")
    TownGuardPerk.objects.create(order=3, sections="91.4;157.3",
                                 description="Replace two <modPlus0/> cards with one <modPlus10/> card")
    TownGuardPerk.objects.create(order=4, sections="130.3;104.1",
                                 description="Replace two <modPlus10/> cards with two <modPlus10/> \"Gain Advantage on this target\" <rolling/> cards")
    TownGuardPerk.objects.create(order=5, sections="167.2;175.1",
                                 description="Add one <modPlus30/> card")
    TownGuardPerk.objects.create(
        order=6, sections="180.3", description="Add two <modPlus0/> \"Gain one Hide\" <rolling/> cards")
    TownGuardPerk.objects.create(
        order=7, sections="41.1", description="Add two <modPlus0/> \"Gain one Lumber\" <rolling/> cards")
    TownGuardPerk.objects.create(
        order=8, sections="192.1", description="Add two <modPlus0/> \"Gain one Metal\" <rolling/> cards")


def remove_perks(apps, schema_editor):
    TownGuardPerk = apps.get_model('campaigns', 'TownGuardPerk')
    TownGuardPerk.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_townguardperk_options_and_more'),
    ]

    operations = [
        migrations.RunPython(create_perks, remove_perks),
    ]
