# Generated by Django 4.2 on 2023-05-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_add_perks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.AddField(
            model_name='campaign',
            name='current_week',
            field=models.IntegerField(default=0),
        ),
    ]
