# Generated by Django 4.2 on 2023-05-27 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0004_remove_event_description_campaign_current_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='current_week',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='CampaignInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='accepted_at')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='rejected_at')),
                ('created_at', models.DateTimeField(verbose_name='created_at')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
