# Generated by Django 4.2 on 2023-05-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_alter_campaign_current_week_campaigninvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncharacter',
            name='retired_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='retired at'),
        ),
    ]
